### ISSUE TITLE
VQEDummyAccelerator

### ISSUE THREAD

**Issue by chMoussa** [ORNL-QCI/xacc-vqe#21]
Hello,

I get this error when trying VQE on a simple example by setting a IBM accelerator.

![vqedummy](https://user-images.githubusercontent.com/18176484/43475636-fdb5a9a4-94bb-11e8-8831-3524e9711713.PNG)

Here is the example code :

import pyxaccvqe as vqe
import pyxacc as xacc
from pyxaccvqe import PauliOperator

xacc.Initialize(["--compiler","quil"])
accelerator = "ibm"
backend = "ibmq_qasm_simulator"

qpu = xacc.getAccelerator(accelerator)
xacc.setOption(accelerator+"-backend",backend)

# Getting Ansatz kernel
srcH2 = """__qpu__ ansatz(AcceleratorBuffer, double t0) {
X 0
RY(t0) 1
CNOT 1 0
}"""

ansatzH2 = xacc.compileKernel(qpu,srcH2)

# Defining problem
bond_length = 0.7474
H2 = PauliOperator(5.906709445) + \
            PauliOperator({0:'X',1:'X'}, -2.1433) + \
                PauliOperator({0:'Y',1:'Y'}, -2.1433) + \
                    PauliOperator({0:'Z'}, .21829) + \
                        PauliOperator({1:'Z'}, -6.125)
print(H2)

# Executing
vqeResult = vqe.execute(H2,**{"task":"vqe", "vqe_params":str(bond_length),"ansatz":ansatzH2})

print('(Optimal Angle, Energy) = (', vqeResult.angles,',', vqeResult.energy, ')')
print('Number of QPU Calls = ', vqeResult.nQpuCalls)
print('Number of VQE Iterations = ', vqeResult.vqeIterations)

**Comment by amccaskey** [comment]
Hey @chMoussa. 

This occurs when one does not have TNQVM installed and does not specify the Accelerator to run with. In your code you get reference to the IBM Accelerator and use it to compile the ansatz, but you do not indicate that you are going to use it in the `vqe.execute()` method. 

Try adding 'accelerator':'ibm' to the vqe.execute kwargs dictionary. 
```python
vqeResult = vqe.execute(H2, **{'task':'vqe', 'ansatz':ansatzH2, 'accelerator':'ibm'})
```
Or before this call, call 
```python
xacc.setOption('accelerator', 'ibm')
```

Note that the 'vqe-params' key is for setting the state prep ansatz parameters.

**Comment by chMoussa** [comment]
It worked with the setOption with 2 VQE calls.
You still have errors about setExpectationvalueZ not implemented.


![vqeexpectationz](https://user-images.githubusercontent.com/18176484/43479049-1e002348-94c5-11e8-8465-3d9684403622.PNG)

**Comment by amccaskey** [comment]
I would like to see if this goes away after updating to the new xacc-ibm plugin. @czhao39 is going to try this script with his updated xacc-ibm wheel.

**Comment by amccaskey** [comment]
@chMoussa I have uploaded an updated xacc-ibm wheel to PyPi. You can now run 

```bash
$ python -m pip install --upgrade xacc-ibm
```
Let us know if that gets rid of your bug.

**Comment by chMoussa** [comment]
Now working well. Here is a screenshot of the 155th iteration.

![vqeworks](https://user-images.githubusercontent.com/18176484/43489881-15337b60-94e4-11e8-9f9c-0de3cb67e088.PNG)
